# Inspired by https://docs.docker.com/compose/django/
version: '3'

services:
  db:
    # NOTE: No persistance storage configured.
    # See: https://hub.docker.com/_/postgres/
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./docker-init-db.sql:/docker-entrypoint-initdb.d/init_db.sql

  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=sharing.conf.docker
      - SECRET_KEY=${SECRET_KEY:-django-insecure-hbwcifrcld9wln-m#w#rwscn(@ktf3ot_=sad^nlprhkf9pr*x}
      - DB_NAME=sharing
      - DB_USER=sharing
      - DB_HOST=db
      - TWO_FACTOR_FORCE_OTP_ADMIN=0
      - TWO_FACTOR_PATCH_ADMIN=0
      - ALLOWED_HOSTS=*
    ports:
      - 8000:8000
    depends_on:
      - db
