# Generated by Django 3.2.12 on 2022-02-24 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientAuth",
            fields=[
                (
                    "token",
                    models.CharField(
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                        verbose_name="token",
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        help_text="Organization which has access to the API",
                        max_length=200,
                        verbose_name="organization",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email to contact the organization",
                        max_length=254,
                        verbose_name="email",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when the token was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date when the token was last changed",
                        verbose_name="updated on",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client authorization",
                "verbose_name_plural": "Client authorizations",
            },
        ),
        migrations.CreateModel(
            name="ClientConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="label to name the config",
                        max_length=100,
                        verbose_name="label",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Slug of the config. Used in the API",
                        max_length=100,
                        verbose_name="slug",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("github", "Github")],
                        default="github",
                        help_text="Type of the config",
                        max_length=50,
                        verbose_name="type",
                    ),
                ),
                (
                    "access_token",
                    models.CharField(
                        blank=True,
                        help_text="Access token for GitHub authorization. Can be generated at https://github.com/settings/tokens",
                        max_length=250,
                        verbose_name="access token",
                    ),
                ),
                (
                    "repo",
                    models.CharField(
                        blank=True,
                        help_text="GitHub repository in the format {owner}/{name}",
                        max_length=250,
                        verbose_name="repo",
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        blank=True,
                        help_text="GitHub branch to use, if empty the default branch is used",
                        max_length=250,
                        verbose_name="branch",
                    ),
                ),
                (
                    "client_auth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configs",
                        to="core.clientauth",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client configuration",
                "verbose_name_plural": "Client configurations",
                "unique_together": {("client_auth", "slug")},
            },
        ),
    ]
