# Generated by Django 3.2.12 on 2022-04-05 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RootPathConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "folder",
                    models.CharField(
                        help_text="Folder in the root",
                        max_length=200,
                        verbose_name="folder",
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[("read", "Read-only"), ("write", "Read and write")],
                        help_text="Permission for the folder",
                        max_length=20,
                        verbose_name="permission",
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        help_text="Config for which the root path is defined",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="root_paths",
                        to="core.config",
                    ),
                ),
            ],
            options={
                "verbose_name": "Root path configuration",
                "verbose_name_plural": "Root path configurations",
            },
        ),
    ]
