# Generated by Django 3.2.12 on 2022-03-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientconfig",
            name="type",
            field=models.CharField(
                choices=[("github", "Github"), ("debug", "Testing")],
                default="github",
                help_text="Type of the config",
                max_length=50,
                verbose_name="type",
            ),
        ),
    ]
