# Generated by Django 3.2.12 on 2022-04-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rootpathconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="options",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Configuration-specific options. The shape of the field is described in the `handler.configuration_options` ",
                null=True,
                verbose_name="options",
            ),
        ),
    ]
