# Generated by Django 3.2.12 on 2022-04-14 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_move_github_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="config",
            name="access_token",
        ),
        migrations.RemoveField(
            model_name="config",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="config",
            name="repo",
        ),
    ]
