# Generated by Django 3.2.12 on 2022-04-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_auto_20220414_1542"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="type",
            field=models.CharField(
                default="debug",
                help_text="Type of the config",
                max_length=50,
                verbose_name="type",
            ),
        ),
    ]
