openapi: 3.0.3
info:
  title: Sharing Configurations API
  version: 0.1.0
  description: An API to share configuration files using different backends
paths:
  /api/v1/config/{slug}/folder/{folder}/files/:
    post:
      operationId: file_upload
      description: Upload configuration file
      summary: File upload
      parameters:
      - in: path
        name: folder
        schema:
          type: string
        description: Path to the folder where the configuration file is located
        required: true
      - in: path
        name: slug
        schema:
          type: string
        description: Slug label of the client configuration. Used to define the type
          of backend
        required: true
      tags:
      - config
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FileContent'
        required: true
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileContent'
          description: ''
  /api/v1/config/{slug}/folder/{folder}/files/{filename}/:
    get:
      operationId: file_download
      description: Download configuration file
      summary: File download
      parameters:
      - in: path
        name: filename
        schema:
          type: string
        description: Name of the configuration file
        required: true
      - in: path
        name: folder
        schema:
          type: string
        description: Path to the folder where the configuration file is located
        required: true
      - in: path
        name: slug
        schema:
          type: string
        description: Slug label of the client configuration. Used to define the type
          of backend
        required: true
      tags:
      - config
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileContent'
          description: ''
components:
  schemas:
    FileContent:
      type: object
      properties:
        url:
          type: string
          readOnly: true
          description: Url of the file in the Sharing Configs API
        filename:
          type: string
          description: Name of the file
          maxLength: 100
        content:
          type: string
          format: uri
          description: File content with base64 encoding
      required:
      - content
      - filename
  securitySchemes:
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
